### ISSUE TITLE
Requesting for changelog

### ISSUE THREAD

**Issue by stagefright5** [antfu/vscode-theme-vitesse#2]
Is it possible for you to maintain a changelog?
It would help us users to see what is fixed, what was added etc.

Thanks

**Comment by antfu** [comment]
Yeah, can do that but since this is just a theme and the changes are mostly about colors (and also relative subtle), I don't feel it's worth to take too much effort on maintaining the changelog for it. As the changelog can't properly reflect the color changes either, the best way for this might be just look at the commits and diff. Thanks for bringing this up.
